### PR TITLE
Fix NullPointerException when property is null

### PR DESCRIPTION
**Pull request by LinkedList**
Issue: DATAKV-114

I have signed and agree to the terms of the Spring Individual Contributor
License Agreement.

### CODE REVIEW

**Comment by olivergierke** [comment]
Would you mind adding a test case, too?

**Comment by LinkedList** [comment]
Sure.

**Comment by olivergierke** [comment]
That's polished and merged, thanks!

**Comment by LinkedList** [comment]
Sorry for added work.

**Pull request closed without merging**
