### PR TITLE
Changes error message to a more befitting one.

### PR DESCRIPTION
**Pull request by AbassAdeyemi**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@AbassAdeyemi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-keyvalue&pullRequestId=345)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-keyvalue&pullRequestId=345) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by mp911de** [comment]
Trivial fix, no CLA required.

**Comment by mp911de** [comment]
@pivotal-issuemaster this is a trivial change

**Comment by pivotal-issuemaster** [comment]
@AbassAdeyemi This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by AbassAdeyemi** [comment]
Thank you very much for the clarification. Fortunately, I was able to also
figure that out early. Please, let me know if there are further actions
required of me for the changes to be eligible for merging.

**Comment by mp911de** [comment]
Thanks a lot. No further action is required, I need to merge this PR tomorrow or so.

**Pull request merged**
