### PR TITLE
DATAKV-322 - Support setting the QueryEngine in the MapKeyValueAdapter 

### PR DESCRIPTION
**Pull request by marceloverdijk**
~This PR adds support for `java.util.function.Predicate` based queries.~
~I had to adapt the `MapKeyValueAdapter` to be able to set the engine (there was no way currently).~

~If you like this PR I can update and provide documentation as well. Just let me know in what section of the guide you would prefer it.~

I've updated the PR so the `Predicate` related classes are removed.
This PR essentially now only includes support for setting a custom `QueryEngine`  in the `MapKeyValueAdapter`.

This way users can provide their own `QueryEngine` like a `PredicateQueryEngine` based on  `java.util.function.Predicate`.

### CODE REVIEW

**Comment by marceloverdijk** [comment]
@schauder @christophstrobl Any chance of getting this added?

**Comment by mp911de** [comment]
Thanks for submitting a pull request. This isn't a feature that we would like to include, however it makes sense to allow for more extensibility. 

There are two reasons for why we don't want to include `Predicate`-support:

1. `Map`-based repositories are a reference implementation for the Key-Value support. The actual intent of this project is that Key-Value-like stores (Redis, Hazelcast, …) can build repository support for their datastores by providing an adapter and a query engine that translates the repository query method into the actual query system used by the data stores. Therefore, the Map-based repositories aren't built for further evolution.
2. There's little ask for `Map`-based repositories in terms of features or support requests. We don't want to add another mechanism that we need to maintain.

That being said, let's keep the changes to `KeyValueQuery` and `MapKeyValueAdapter` so that you can build `Predicate` support in your own codebase.

**Comment by marceloverdijk** [comment]
@mp911de I've updated the PR as discussed on Gitter.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and polished now.

**Pull request closed without merging**
